default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: rails_project_65_production
  username: rails_project_65
  password: <%= ENV["RAILS_PROJECT_65_DATABASE_PASSWORD"] %>
